# Generated by Django 4.2.13 on 2025-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
