# Generated by Django 4.2.13 on 2025-07-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_codesubmission_plagiarism_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='plagiarism_score',
        ),
    ]
