# Generated by Django 4.2.13 on 2025-07-26 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_contest_codesubmission_score_problem_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
        migrations.AddField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 26, 17, 28, 22, 481189)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.contest'),
        ),
    ]
