# Generated by Django 4.2.13 on 2025-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_contest_problems_contest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
