# Generated by Django 4.2.13 on 2025-07-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_remove_problem_contest_contest_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_set', to='problems.contest'),
        ),
    ]
